"""add policy chunks

Revision ID: 0004
Revises: 0003
Create Date: 2026-09-14 12:34:47.756418+00:00
"""

from collections.abc import Sequence

import pgvector.sqlalchemy
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0004"
down_revision: str | Sequence[str] | None = "0003"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # Hand-added: autogenerate cannot know the vector column type needs an extension.
    # Needs a superuser, which the POSTGRES_USER of the pgvector image is.
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "policy_chunks",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("document", sa.String(length=200), nullable=False),
        sa.Column("heading", sa.String(length=400), nullable=False),
        sa.Column("ordinal", sa.Integer(), nullable=False),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column("embedding", pgvector.sqlalchemy.vector.VECTOR(dim=768), nullable=False),
        sa.Column("source_sha256", sa.String(length=64), nullable=False),
        sa.Column("embedding_fingerprint", sa.String(length=200), nullable=False),
        sa.Column(
            "indexed_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_policy_chunks")),
    )
    op.create_index(op.f("ix_policy_chunks_document"), "policy_chunks", ["document"], unique=False)
    op.create_index(
        "ix_policy_chunks_embedding",
        "policy_chunks",
        ["embedding"],
        unique=False,
        postgresql_using="hnsw",
        postgresql_with={"m": 16, "ef_construction": 64},
        postgresql_ops={"embedding": "vector_cosine_ops"},
    )
    op.create_index(
        op.f("ix_policy_chunks_source_sha256"), "policy_chunks", ["source_sha256"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_policy_chunks_source_sha256"), table_name="policy_chunks")
    op.drop_index(
        "ix_policy_chunks_embedding",
        table_name="policy_chunks",
        postgresql_using="hnsw",
        postgresql_with={"m": 16, "ef_construction": 64},
        postgresql_ops={"embedding": "vector_cosine_ops"},
    )
    op.drop_index(op.f("ix_policy_chunks_document"), table_name="policy_chunks")
    op.drop_table("policy_chunks")
    # ### end Alembic commands ###
    # The extension is deliberately left in place: dropping it would break any other
    # object using the vector type, and re-creating it costs nothing.
