"""add ticket category

Revision ID: 0005
Revises: 0004
Create Date: 2026-09-14 19:29:38.660700+00:00
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0005"
down_revision: str | Sequence[str] | None = "0004"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "tickets",
        sa.Column(
            "category",
            sa.Enum(
                "shipping",
                "return_or_refund",
                "warranty",
                "order_status",
                "product",
                "other",
                name="ticket_category",
                native_enum=False,
                create_constraint=True,
                length=32,
            ),
            nullable=True,
        ),
    )
    op.create_index(op.f("ix_tickets_category"), "tickets", ["category"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_tickets_category"), table_name="tickets")
    op.drop_column("tickets", "category")
    # ### end Alembic commands ###
